export enum ModuleType {
    Company = 'Company',
    Factory = 'Factory',
    Warehouse = 'Warehouse',
    Store = 'Store',
    ServiceCenter = 'ServiceCenter',
    Distributor = 'Distributor',
    Retailer = 'Retailer',
    Model = 'Model',
    Product = 'Product',
    Complaint = 'Complaint',
    Item = 'Item',
    Employee = 'Employee',
    Customer = 'Customer',
    Purchase = 'Purchase',
    Review = 'Review',
    Rating = 'Rating',
    Task = 'Task',
    Warranty = 'Warranty',
}